module.exports = {
  ALLOW: "ALLOW",
  SOFT_THROTTLE: "SOFT_THROTTLE",
  LIMIT_CONCURRENCY: "LIMIT_CONCURRENCY",
  TEMP_COOLDOWN: "TEMP_COOLDOWN",
  BLOCK_TEMP: "BLOCK_TEMP",
  BLOCK_HARD: "BLOCK_HARD",
  ALERT_ONLY: "ALERT_ONLY"
}